try
Signed-off-by: GentleEnvy <komarov.sergei163@gmail.com>

diff --git a/.github/workflows/call-envs.yml b/.github/workflows/call-envs.yml
--- a/.github/workflows/call-envs.yml
+++ b/.github/workflows/call-envs.yml
@@ -7,8 +7,35 @@ on:
       env_keys:
         type: string
         required: false
-        default: "WEB_DOMAIN, API_DOMAIN, SECRET_KEY, DEBUG, TEST, ANON_THROTTLE_RATE,
-          USER_THROTTLE_RATE, USE_BROWSABLE_API, EMAIL_URL, EMAIL_BACKEND"
+        default: '
+          WEB_DOMAIN,
+          API_DOMAIN,
+          SECRET_KEY,
+          DEBUG,
+          TEST,
+          ANON_THROTTLE_RATE,
+          USE_BROWSABLE_API,
+          EMAIL_URL,
+          EMAIL_BACKEND,
+          CELERY_TASK_EAGER,
+          CELERY_REDIS_MAX_CONNECTIONS,
+          CELERY_BROKER_POOL_LIMIT,
+          CLOUDINARY_URL,
+          CLOUDINARY_PREFIX,
+          USE_SILK,
+          SENTRY_DSN,
+          SENTRY_ENVIRONMENT,
+          POSTGRES_PASSWORD,
+          DATABASE_URL,
+          REDIRECT_ON_UNSUBSCRIBE,
+          GOOGLE_APP_ID,
+          GOOGLE_APP_SECRET,
+          ADMINS,
+          LOG_PRETTY,
+          LOG_REQUESTS,
+          LOG_LEVEL,
+          FIXER_ACCESS_KEY
+        '
     outputs:
       envs:
         value: ${{ jobs.envs.outputs.envs }}
@@ -29,8 +56,11 @@ jobs:
           envs_json=$(jq -s '.[0] * .[1]' <(echo $vars_json) <(echo $secrets_json))
           envs=''
           for env_key in "${env_keys[@]}"; do
-            echo $env_key
             env_var=$(echo $envs_json | jq -r --arg env_key "$env_key" '.[$env_key]')
+            if [ "$env_var" == "null" ]; then
+              echo "::error::KeyError: $env_key"
+              exit 1
+            fi
             envs=$envs$env_key=$env_var\\n
           done
           echo envs=$envs >> $GITHUB_OUTPUT
